version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nest-pokemon
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - ./mongo:/data/db


